# Site settings
title: Albert Zak
email: me@albertzak.com
description: > 
  I believe in making useful things
  and living an unconventional life.
baseurl: ""
url: "https://albertzak.com"
google_analytics_id: UA-36344621-2

# Build settings
exclude:
  - s3_website.yml
  - Gemfile
  - Gemfile.lock
  - .gitignore
sass:
  style: compressed
markdown: kramdown
gems:
  - jekyll-timeago
jekyll_timeago:
  prefix: ''
  suffix: ''
  depth:  1
production: false
builddate: <%= `date` %>
commit: <%= `git rev-parse HEAD` %>
cachebust: <%= `md5 -q _site/css/main.css` %>
