# Site settings
title: Albert Zak
email: me@albertzak.com
description: > 
  I believe in making useful things
  and living an unconventional life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://albertzak.com" # the base hostname & protocol for your site
google_analytics_id: UA-36344621-2

# Build settings
markdown: kramdown

